services:
    helldiversbot:
        container_name: helldivers1api
        # init: true
        restart: unless-stopped
        image: ghcr.io/elfensky/helldivers1api:staging
        ports:
            - '58102:3000'
        env_file:
            - .env.docker
