import './layout.css';
//nextjs
import Script from 'next/script';
import { headers } from 'next/headers';
import { Space_Grotesk, Inter } from 'next/font/google';
import { Toaster } from 'sonner';
//components
import Header from '@/shared/components/Header/Header';
import Footer from '@/shared/components/Footer/Footer';
import BottomNav from '@/shared/components/BottomNav/BottomNav';
import ServiceWorkerRegister from '@/shared/components/ServiceWorkerRegister';

const spaceGrotesk = Space_Grotesk({
    subsets: ['latin'],
    variable: '--font-space-grotesk',
    display: 'swap',
});

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter',
    display: 'swap',
});

// function getMetaURL() {
//     switch (process.env.NODE_ENV) {
//         case 'development':
//             return new URL('http://localhost:3000');
//         case 'staging':
//             return new URL('https://staging.helldivers.bot');
//         case 'production':
//             return new URL('https://helldivers.bot');
//         default:
//             throw new Error('Unknown NODE_ENV');
//     }
// }

export const viewport = {
    themeColor: '#1c1b1b',
};

export const metadata = {
    metadataBase: new URL('https://helldivers.bot'),
    title: 'Helldivers Bot - Live war dashboard for the original Helldivers',
    description:
        'Live Helldivers 1 war dashboard showing campaign progress, faction stats, active events, and an interactive galaxy map.',
    manifest: '/site.webmanifest',
    appleWebApp: {
        capable: true,
        statusBarStyle: 'black-translucent',
        title: 'Helldivers Bot',
    },
    alternates: {
        canonical: '/',
    },
    openGraph: {
        type: 'website',
        url: '/',
    },
    twitter: {
        card: 'summary_large_image',
    },
};

export default async function RootLayout({ children }) {
    const nonce = (await headers()).get('x-nonce') ?? undefined;
    const isProduction = process.env.NODE_ENV === 'production';

    return (
        <html
            dir="ltr"
            lang="en"
            className={`${spaceGrotesk.variable} ${inter.variable}`}
        >
            <head>
                {/* iOS splash screens (portrait only) — generated by pwa-asset-generator */}
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-2048-2732.png"
                    media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1668-2388.png"
                    media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1536-2048.png"
                    media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1640-2360.png"
                    media="(device-width: 820px) and (device-height: 1180px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1668-2224.png"
                    media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1620-2160.png"
                    media="(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1488-2266.png"
                    media="(device-width: 744px) and (device-height: 1133px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1320-2868.png"
                    media="(device-width: 440px) and (device-height: 956px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1206-2622.png"
                    media="(device-width: 402px) and (device-height: 874px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1260-2736.png"
                    media="(device-width: 420px) and (device-height: 912px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1290-2796.png"
                    media="(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1179-2556.png"
                    media="(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1170-2532.png"
                    media="(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1284-2778.png"
                    media="(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1125-2436.png"
                    media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1242-2688.png"
                    media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-828-1792.png"
                    media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-1242-2208.png"
                    media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-750-1334.png"
                    media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
                <link
                    rel="apple-touch-startup-image"
                    href="/splash/apple-splash-640-1136.png"
                    media="(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
                />
            </head>
            <body id="body" className="flex min-h-screen min-w-full flex-col antialiased">
                <script
                    nonce={nonce}
                    type="application/ld+json"
                    suppressHydrationWarning
                    dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
                />

                <a
                    href="#main"
                    className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-50 focus:bg-primary focus:px-4 focus:py-2 focus:text-on-primary"
                >
                    Skip to content
                </a>
                <div
                    className="fixed inset-0 z-[999] flex items-center justify-center bg-surface-0 p-4 text-center text-sm text-text-muted min-[200px]:hidden"
                    role="alert"
                >
                    <p className="m-0">Please use a larger screen to view this site.</p>
                </div>
                <Header />
                <main
                    id="main"
                    className="flex min-h-screen w-full flex-col pt-[50px] pb-[48px] sm:pt-[80px] md:pb-0"
                >
                    {children}
                </main>
                <Footer />
                <BottomNav />
                <ServiceWorkerRegister />
                <Toaster
                    theme="dark"
                    position="bottom-right"
                    toastOptions={{
                        style: {
                            borderRadius: '0px',
                            background: 'var(--color-surface-1)',
                            color: 'var(--color-text)',
                            border: '1px solid var(--color-ghost)',
                            fontFamily: 'var(--font-body)',
                        },
                    }}
                />

                {isProduction ?
                    <Script
                        nonce={nonce}
                        // src="https://umami.lavrenov.io/script.js"
                        src="/stats.js"
                        data-website-id="9a916711-2868-43d2-9932-964fc9528824"
                        strategy="afterInteractive"
                        data-host-url="https://umami.lavrenov.io"
                    />
                :   null}
            </body>
        </html>
    );
}

const schema = {
    '@context': 'https://schema.org',
    '@type': 'WebSite', // '@type': ['WebSite', 'WebApplication', 'VideoGame']
    applicationCategory: ['GameUtility', 'GameInformation', 'Entertainment'],
    url: 'https://helldivers.bot',

    name: 'Helldivers Bot',
    // author: 'Andrei Lavrenov',
    author: {
        '@type': 'Person',
        name: 'Andrei Lavrenov',
        url: 'https://lavrenov.io',
    },
    description:
        'A website that provides dedicated real-time in-game status updates for the original Helldivers videogame.',

    // only possible for specific @types
    // aggregateRating: {
    //     '@type': 'AggregateRating',
    //     ratingValue: 5.0,
    //     ratingCount: 3,
    // },

    offers: {
        '@type': 'Offer',
        price: 0.0,
        priceCurrency: 'EUR',
        // availability: 'http://schema.org/InStock',
        // url: 'https://helldivers.bot/campaign',
    },

    // image: "https://helldivers.bot/url-to-dynamically-generated-map-status"

    // mainEntity: [
    //     {
    //         '@type': 'VideoGame',
    //         name: 'Helldivers',
    //         url: 'https://helldivers.bot',
    //         gamePlatform: 'PC, PlayStation',
    //         applicationCategory: 'Action, Shooter',
    //         description:
    //             'Helldivers is a top-down cooperative shooter game where players fight to protect Super Earth from Xeno threats.',
    //         publisher: {
    //             '@type': 'Organization',
    //             name: 'Arrowhead Game Studios',
    //             url: 'https://arrowheadgamestudios.com',
    //         },
    //     },
    //     {
    //         '@type': 'SoftwareApplication',
    //         name: 'Helldivers 1 Bot',
    //         applicationCategory: 'Discord Bot, Chat bot',
    //         operatingSystem: 'Discord',
    //         url: 'https://helldivers.bot/discord',
    //         description:
    //             'A Discord bot that provides updates about in-game events and statistics.',
    //         softwareVersion: '1.0.0',
    //         creator: {
    //             '@type': 'Person',
    //             name: 'Andrei Lavrenov',
    //             url: 'https://lavrenov.io',
    //         },
    //         offers: {
    //             '@type': 'Offer',
    //             price: '0.00',
    //             priceCurrency: 'EUR',
    //             availability: 'http://schema.org/InStock',
    //             url: 'https://helldivers.bot/discord',
    //         },
    //         // aggregateRating: {
    //         //     '@type': 'AggregateRating',
    //         //     ratingValue: '0.8',
    //         //     bestRating: '1',
    //         //     ratingCount: '1',
    //         // },
    //     },
    //     {
    //         '@type': 'WebAPI',
    //         name: 'Helldivers 1 API',
    //         url: 'https://helldivers.bot/api',
    //         description:
    //             'An API providing access to Helldivers campaign status and statistics. Written in JavaScript and powered by Next.js.',
    //         documentation: 'https://helldivers.bot/docs',
    //         provider: {
    //             '@type': 'Person',
    //             name: 'Andrei Lavrenov',
    //             url: 'https://lavrenov.io',
    //         },
    //     },
    // ],
};

// const toAddToJsonLd = {
//     potentialAction: [
//         {
//             '@type': 'ViewAction',
//             target: 'https://helldivers.bot/view/{content_id}',
//             'query-input': 'required name=content_id',
//         },
//         {
//             '@type': 'SearchAction',
//             target: 'https://helldivers.bot/search?q={search_term_string}',
//             'query-input': 'required name=search_term_string',
//         },
//         {
//             '@type': 'RegisterAction',
//             target: 'https://helldivers.bot/register',
//         },
//         {
//             '@type': 'LikeAction',
//             target: 'https://helldivers.bot/like/{content_id}',
//             'query-input': 'required name=content_id',
//         },
//         {
//             '@type': 'DislikeAction',
//             target: 'https://helldivers.bot/dislike/{content_id}',
//             'query-input': 'required name=content_id',
//         },
//         {
//             '@type': 'ShareAction',
//             target: 'https://helldivers.bot/share/{content_id}',
//             'query-input': 'required name=content_id',
//         },
//     ],
// };
