name: Build Dev Image
on:
    workflow_dispatch: # allows requesting workflow manually from the website
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACCESS_TOKEN }} # use personal access token

            - name: Extract version from package.json
              id: extract_version
              run: echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  platforms: linux/amd64 #,linux/arm64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/helldivers1api:dev
